apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  labels:
    app: myflaskapp-old
    app.kubernetes.io/component: myflaskapp-old
    app.kubernetes.io/instance: myflaskapp-old
  name: myflaskapp-old
  namespace: myproject
spec:
  lookupPolicy:
    local: false
