kind: PersistentVolume
apiVersion: v1
metadata:
  name: myvolume
  labels:
    volume: myvolume
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/pv-data/sridhar
    type: ''
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Available
