kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-new-storage-claim
  namespace: myproject
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: myvolume
  volumeMode: Filesystem
status:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: 100Gi
